### ISSUE TITLE
Server Down ...

### ISSUE THREAD

**Issue by warronyiang15** [farnking/Test-Dragon-Forum-of-TBots#38]
## Problem Description

Seems like the server is down since 30/12/2023 00:00 A.M. , is this normal?

<img width="1205" alt="Screenshot 2023-12-30 at 1 19 00 PM" src="https://github.com/farnking/Test-Dragon-Forum-of-TBots/assets/65525835/a47acabe-46c0-4b13-b4e2-acb0a615db9c">

**Comment by farnking** [comment]
Just restart the server!  Happy new year.

**Comment by warronyiang15** [comment]
Thanks, its work now ! :D
